# Generated by Django 5.2.9 on 2025-12-03 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('idade', models.IntegerField()),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_de_ingresso', models.DateField()),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('nome_curso', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('duracao', models.IntegerField()),
                ('modalidade', models.CharField(max_length=50)),
                ('carga_horaria', models.IntegerField()),
                ('valor_de_inscricao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='inativo', max_length=20)),
            ],
            options={
                'ordering': ['nome_curso'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('numero_da_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('data_de_matricula', models.DateField()),
                ('status', models.CharField(default='pendente', max_length=20)),
                ('status_aluno', models.CharField(default='Matriculado', max_length=20)),
                ('nota', models.FloatField(default=0.0)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.curso')),
            ],
            options={
                'ordering': ['data_de_matricula'],
            },
        ),
    ]
